=== ssz/Database/HW3/585HW3/company.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XSD document created with EditiX XML Editor (http://www.editix.com) at Tue Nov 25 10:27:37 PST 2014 -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- definition of simple elements -->
<xs:element name="deptid">
	<xs:simpleType>
  		<xs:restriction base="xs:string">
      		<xs:pattern value="[A-Z][A-Z][A-Z]"/>
    		</xs:restriction>
  	</xs:simpleType>
</xs:element>

<xs:element name="deptname">
	<xs:simpleType>
    		<xs:restriction base="xs:string">
    		</xs:restriction>
  	</xs:simpleType>
</xs:element>

<xs:element name="deptaddr">
  	<xs:simpleType>
    		<xs:restriction base="xs:string">
    		</xs:restriction>
  	</xs:simpleType>
</xs:element>


<xs:element name="empid">
  	<xs:simpleType>
    		<xs:restriction base="xs:integer">
    		</xs:restriction>
  	</xs:simpleType>
</xs:element>

<xs:element name="empname">
  	<xs:simpleType>
    		<xs:restriction base="xs:string">
    		</xs:restriction>
  	</xs:simpleType>
</xs:element>

<xs:element name="empphone">
  	<xs:simpleType>
    		<xs:restriction base="xs:string">
    	 	<xs:pattern value="[1-9][0-9][0-9]-[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]"/>
    		</xs:restriction>
  	</xs:simpleType>
</xs:element>

<xs:element name="empoffice">
  	<xs:simpleType>
    		<xs:restriction base="xs:string">
    		</xs:restriction>
  	</xs:simpleType>
</xs:element>


<xs:element name="divid">
  	<xs:simpleType>
    		<xs:restriction base="xs:string">
    		</xs:restriction>
  	</xs:simpleType>
</xs:element>

<xs:element name="divname">
  	<xs:simpleType>
    		<xs:restriction base="xs:string">
    		</xs:restriction>
  	</xs:simpleType>
</xs:element>

<xs:element name="divphone">
  	<xs:simpleType>
    		<xs:restriction base="xs:string">
    	 	<xs:pattern value="[1-9][0-9][0-9]-[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]"/>
    	</xs:restriction>
  	</xs:simpleType>
</xs:element>

<xs:element name="houseddeptid">
	<xs:simpleType>
    		<xs:restriction base="xs:string">
    		</xs:restriction>
  	</xs:simpleType>
</xs:element>

<xs:element name="managerempid">
	<xs:simpleType>
    		<xs:restriction base="xs:integer">
    		</xs:restriction>
  	</xs:simpleType>
</xs:element>

<!--
<xs:element name="houseddeptid">
  	<xs:simpleType>
    		<xs:restriction base="xs:string">
    		<xs:pattern value="[A-Z][A-Z][A-Z]"/>
    		</xs:restriction>
  	</xs:simpleType>
</xs:element>
-->
<xs:element name="percenttime">
  	<xs:simpleType>
    		<xs:restriction base="xs:integer">
    		</xs:restriction>
  	</xs:simpleType>
</xs:element>


<!-- definition of complex elements -->
<xs:element name="company">
<xs:complexType>
	<xs:sequence>
		<xs:element ref="department" maxOccurs="unbounded"/>
      		<xs:element ref="employee" maxOccurs="unbounded"/>
      		<xs:element ref="division" maxOccurs="unbounded"/>
      		<xs:element ref="worksfor" maxOccurs="unbounded"/>
    	</xs:sequence>
</xs:complexType>
<xs:key name="PKdeptid">
	<xs:selector xpath="department/deptid"/>
      	<xs:field xpath="."/>
</xs:key>
<xs:key name="PKdivid">
	<xs:selector xpath="division/divid"/>
      	<xs:field xpath="."/>
</xs:key>
<xs:key name="PKempid">
       <xs:selector xpath="employee/empid"/>
       <xs:field xpath="."/>
</xs:key>
<xs:keyref name="FKhousedDeptId" refer="PKdeptid">
	<xs:selector xpath="division/houseddeptid"/>
      	<xs:field xpath="."/>
</xs:keyref>
<xs:keyref name="FKmanagerEmpId" refer="PKempid">
	<xs:selector xpath="division/managerempid"/>
      	<xs:field xpath="."/>
</xs:keyref>
<xs:keyref name="FKdname" refer="PKdivid">
	<xs:selector xpath="worksfor/divid"/>
      	<xs:field xpath="."/>
</xs:keyref>
<xs:keyref name="FKssn" refer="PKempid">
	<xs:selector xpath="worksfor/empid"/>
      	<xs:field xpath="."/>
</xs:keyref>
</xs:element>

<xs:element name="department">
<xs:complexType>
	<xs:sequence>
		<xs:element ref="deptid"/>
      		<xs:element ref="deptname"/>
      		<xs:element ref="deptaddr"/>
    	</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="employee">
<xs:complexType>
	<xs:sequence>
		<xs:element ref="empid"/>
      		<xs:element ref="empname"/>
      		<xs:element ref="empphone"/>
      		<xs:element ref="empoffice"/>
    	</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="division">
<xs:complexType>
	<xs:sequence>
		<xs:element ref="divid"/>
      		<xs:element ref="divname"/>
      		<xs:element ref="divphone"/>
      		<xs:element ref="houseddeptid"/>
      		<xs:element ref="managerempid"/>
    	</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="worksfor">
<xs:complexType>
	<xs:sequence>
		<xs:element ref="divid"/>
      		<xs:element ref="empid"/>
      		<xs:element ref="percenttime"/>
    	</xs:sequence>
</xs:complexType>
</xs:element>


</xs:schema>

=== ssz/Database/HW3/585HW3/company.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Mon Nov 24 16:07:30 PST 2014 -->
<?xml-stylesheet type="text/xsl" href="company.xsl"?>
<company xsi:noNamespaceSchemaLocation="company.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<department>
		<deptid>ADM</deptid>
		<deptname>Admin</deptname>
		<deptaddr>LA</deptaddr>
	</department>	
	
	<department>
		<deptid>FIN</deptid>
		<deptname>Finance</deptname>
		<deptaddr>LA</deptaddr>
	</department>
	
	<department>
		<deptid>SER</deptid>
		<deptname>Services</deptname>
		<deptaddr>LA</deptaddr>
	</department>
	
	<department>
		<deptid>OPR</deptid>
		<deptname>Operations</deptname>
		<deptaddr>LA</deptaddr>
	</department>
	
	<department>
		<deptid>BUS</deptid>
		<deptname>Business</deptname>
		<deptaddr>LA</deptaddr>
	</department>

	<employee>
		<empid>1</empid>
		<empname>PSmith</empname>
		<empphone>443-235-3253</empphone>
		<empoffice>LA</empoffice>
	</employee>
	
	<employee>
		<empid>2</empid>
		<empname>Wong</empname>
		<empphone>224-234-9065</empphone>
		<empoffice>LA</empoffice>
	</employee>
	
	<employee>
		<empid>3</empid>
		<empname>Jack</empname>
		<empphone>243-235-4566</empphone>
		<empoffice>LA</empoffice>
	</employee>
	
	<employee>
		<empid>4</empid>
		<empname>Anne</empname>
		<empphone>324-876-3768</empphone>
		<empoffice>LA</empoffice>
	</employee>
	
	<employee>
		<empid>5</empid>
		<empname>Ben</empname>
		<empphone>453-249-3275</empphone>
		<empoffice>LA</empoffice>
	</employee>

	<employee>
		<empid>6</empid>
		<empname>Monica</empname>
		<empphone>935-487-3859</empphone>
		<empoffice>LA</empoffice>
	</employee>
	
	<employee>
		<empid>7</empid>
		<empname>Jennifer</empname>
		<empphone>935-487-3869</empphone>
		<empoffice>LA</empoffice>
	</employee>

	<employee>
		<empid>8</empid>
		<empname>Mary</empname>
		<empphone>932-487-3859</empphone>
		<empoffice>LA</empoffice>
	</employee>	
	
	<division>
		<divid>div1</divid>
		<divname>HR</divname>
		<divphone>346-232-3242</divphone>
		<houseddeptid>ADM</houseddeptid>
		<managerempid>4</managerempid>
	</division>
	
	<division>
		<divid>div2</divid>
		<divname>Recruitment</divname>
		<divphone>346-232-3243</divphone>
		<houseddeptid>ADM</houseddeptid>
		<managerempid>1</managerempid>
	</division>
	
	<division>
		<divid>div3</divid>
		<divname>SysAd</divname>
		<divphone>346-232-3244</divphone>
		<houseddeptid>ADM</houseddeptid>
		<managerempid>3</managerempid>
	</division>
	
	<division>
		<divid>div4</divid>
		<divname>Payroll</divname>
		<divphone>346-232-3245</divphone>
		<houseddeptid>FIN</houseddeptid>
		<managerempid>5</managerempid>
	</division>

	<division>
		<divid>div5</divid>
		<divname>Accounting</divname>
		<divphone>346-232-3246</divphone>
		<houseddeptid>FIN</houseddeptid>
		<managerempid>5</managerempid>
	</division>
	
	<division>
		<divid>div6</divid>
		<divname>Networking</divname>
		<divphone>346-232-3247</divphone>
		<houseddeptid>SER</houseddeptid>
		<managerempid>2</managerempid>
	</division>

	<division>
		<divid>div7</divid>
		<divname>SaaS</divname>
		<divphone>346-232-3248</divphone>
		<houseddeptid>SER</houseddeptid>
		<managerempid>2</managerempid>
	</division>

	<division>
		<divid>div8</divid>
		<divname>Security</divname>
		<divphone>346-232-3249</divphone>
		<houseddeptid>SER</houseddeptid>
		<managerempid>1</managerempid>
	</division>

	<division>
		<divid>div9</divid>
		<divname>Convergence</divname>
		<divphone>346-232-3250</divphone>
		<houseddeptid>SER</houseddeptid>
		<managerempid>1</managerempid>
	</division>
	
	<division>
		<divid>div10</divid>
		<divname>Sales</divname>
		<divphone>346-232-3251</divphone>
		<houseddeptid>OPR</houseddeptid>
		<managerempid>1</managerempid>
	</division>

	<division>
		<divid>div11</divid>
		<divname>Marketing</divname>
		<divphone>346-232-3252</divphone>
		<houseddeptid>OPR</houseddeptid>
		<managerempid>4</managerempid>
	</division>

	<division>
		<divid>div12</divid>
		<divname>Engineering</divname>
		<divphone>346-232-3253</divphone>
		<houseddeptid>OPR</houseddeptid>
		<managerempid>4</managerempid>
	</division>
	
	<division>
		<divid>div13</divid>
		<divname>Business Development</divname>
		<divphone>346-232-3254</divphone>
		<houseddeptid>BUS</houseddeptid>
		<managerempid>1</managerempid>
	</division>

	<division>
		<divid>div14</divid>
		<divname>Business Analysis</divname>
		<divphone>346-232-3255</divphone>
		<houseddeptid>BUS</houseddeptid>
		<managerempid>1</managerempid>
	</division>	
	
	<worksfor>
		<divid>div1</divid>
		<empid>4</empid>
		<percenttime>60</percenttime>
	</worksfor>

	<worksfor>
		<divid>div2</divid>
		<empid>4</empid>
		<percenttime>10</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div3</divid>
		<empid>4</empid>
		<percenttime>10</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div13</divid>
		<empid>4</empid>
		<percenttime>5</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div14</divid>
		<empid>4</empid>
		<percenttime>5</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div2</divid>
		<empid>5</empid>
		<percenttime>10</percenttime>
	</worksfor>

	<worksfor>
		<divid>div3</divid>
		<empid>5</empid>
		<percenttime>10</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div4</divid>
		<empid>5</empid>
		<percenttime>50</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div5</divid>
		<empid>5</empid>
		<percenttime>30</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div2</divid>
		<empid>3</empid>
		<percenttime>20</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div3</divid>
		<empid>3</empid>
		<percenttime>20</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div8</divid>
		<empid>3</empid>
		<percenttime>60</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div2</divid>
		<empid>6</empid>
		<percenttime>10</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div3</divid>
		<empid>6</empid>
		<percenttime>10</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div6</divid>
		<empid>6</empid>
		<percenttime>60</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div7</divid>
		<empid>6</empid>
		<percenttime>20</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div2</divid>
		<empid>1</empid>
		<percenttime>5</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div3</divid>
		<empid>1</empid>
		<percenttime>5</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div6</divid>
		<empid>1</empid>
		<percenttime>15</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div8</divid>
		<empid>1</empid>
		<percenttime>5</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div10</divid>
		<empid>1</empid>
		<percenttime>60</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div13</divid>
		<empid>1</empid>
		<percenttime>5</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div9</divid>
		<empid>1</empid>
		<percenttime>3</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div14</divid>
		<empid>1</empid>
		<percenttime>2</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div2</divid>
		<empid>2</empid>
		<percenttime>10</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div3</divid>
		<empid>2</empid>
		<percenttime>10</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div6</divid>
		<empid>2</empid>
		<percenttime>30</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div7</divid>
		<empid>2</empid>
		<percenttime>10</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div1</divid>
		<empid>2</empid>
		<percenttime>10</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div8</divid>
		<empid>2</empid>
		<percenttime>15</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div4</divid>
		<empid>2</empid>
		<percenttime>15</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div7</divid>
		<empid>7</empid>
		<percenttime>90</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div2</divid>
		<empid>7</empid>
		<percenttime>5</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div3</divid>
		<empid>7</empid>
		<percenttime>5</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div11</divid>
		<empid>8</empid>
		<percenttime>90</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div2</divid>
		<empid>8</empid>
		<percenttime>5</percenttime>
	</worksfor>
	
	<worksfor>
		<divid>div3</divid>
		<empid>8</empid>
		<percenttime>5</percenttime>
	</worksfor>
	
</company>
